#!/usr/bin/env bash

THIS="$(basename $0)"
if [ -z "$1" -o -z "$2" ] || [[ "$1" == '-h' ]] || [[ "$1" == '--help' ]]; then
	echo "Usage: $THIS <FIRMWARE_FILE> <IP_ADDRESS> [<INTERFACE>]"
	exit 1
fi

if [ ! -f "$1" ]; then
	echo "'$1' is not a valid file."
	exit 1
fi

FILE="$1"
IP="$2"
IF="$3"
TFTP_COMMAND="
verbose\n
connect $IP\n
binary\n
rexmt 1\n
timeout 60\n
trace\n
put $FILE\n"

global_ping() { sudo ping -v -t1 -f -c1 $IP; }
function do_ping() {
	if [ -n "$IF" ]; then
		global_ping -b $IF
	else
		global_ping
	fi
}

FILE_DIR="$(dirname "$FILE")"
cd "$FILE_DIR"

exec 5>&1
while [ 0 -eq 0 ]; do
	do_ping
	if [ $? -eq 0 ]; then
		echo '--------> Starting flash' >&5
		( echo -e $TFTP_COMMAND | tftp | tee >(cat - >&5) ) | \
			grep -cE 'Sent \d+ bytes'
		if [ $? -eq 0 ]; then
			echo "The flash apparently succeeded." >&5
			echo '
! ----------------> THIS IS VERY IMPORTANT <-------------- !
You need to now press CTRL+C a lot to get the program to quit. Starting now.
'
			sleep 5
			exit 0
		fi
	fi
done

exit 0
