#!/usr/bin/env bash

APP_URL="https://drive.google.com/drive/my-drive"
PROFILE_DIR="$HOME/Google Office"
mkdir -p "$PROFILE_DIR"
google-chrome --user-data-dir="$PROFILE_DIR" --password-store=kwallet --app="$APP_URL"
