#!/usr/bin/env bash

APP_URL="https://docs.google.com/document/u/0/"
PROFILE_DIR="$HOME/Google Office"
mkdir -p "$PROFILE_DIR"
google-chrome --user-data-dir="$PROFILE_DIR" --password-store=kwallet --app="$APP_URL"
